const mongoose =  require('mongoose');

const ProfilSchema  = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    bio:{
        type:String
    },
    githubUserName:{
        type:String
    },
    experience:[
        {
            title:{
                type:String,
                required:true
            },
            company:{
                type:String,
                required:true
            },
            location:{
                type:String
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                default:false
            }
        }
    ],
    education:[
        {
            school:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            start:{
                type:Date,
                required:true
            },
            end:{
                type:Date
            },
            grade:{
                type:String
            },
            Description:{
                type:String
            }
        }
    ],
    certifications:[{
        name:{
            type:String,
            required:true
        },
        organization:{
            type:String,
            required:true
        },
        start:{
            type:Date,
            required:true
        },
        end:{
            type:Date
        },
        expiration:{
            type:Boolean,
            default:false
        }
    }],
    social:{
        youtube:{
            type:String
        },
        facebook:{
            type:String
        },
        twitter:{
            type:String
        },
        linkedin:{
            type:String
        },
        instagram:{
            type:String
        }
    },
    date:{
        type:Date,
        default:Date.now
    }
});
module.exports = Profile = mongoose.model('profile',ProfilSchema);